// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBleAsfOdYo6NA1Mx2PibF4bAWijUSJTBY',
    appId: '1:707832193088:web:00f4f84add5195a3027fa5',
    messagingSenderId: '707832193088',
    projectId: 'smart-health-queue',
    authDomain: 'smart-health-queue.firebaseapp.com',
    storageBucket: 'smart-health-queue.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBleAsfOdYo6NA1Mx2PibF4bAWijUSJTBY',
    appId: '1:707832193088:android:00f4f84add5195a3027fa5',
    messagingSenderId: '707832193088',
    projectId: 'smart-health-queue',
    authDomain: 'smart-health-queue.firebaseapp.com',
    storageBucket: 'smart-health-queue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBleAsfOdYo6NA1Mx2PibF4bAWijUSJTBY',
    appId: '1:707832193088:ios:00f4f84add5195a3027fa5',
    messagingSenderId: '707832193088',
    projectId: 'smart-health-queue',
    authDomain: 'smart-health-queue.firebaseapp.com',
    storageBucket: 'smart-health-queue.firebasestorage.app',
    iosBundleId: 'com.example.queueapp',
  );
}
